#!/usr/bin/env python
"""
Convierte el romsets.xml del core de Neo Geo en un DAT Parent/Clone que el
builder ya sabe leer. No hace falta tocar build_pack.py.

    python neogeo_dat.py romsets.xml dats/neogeo.dat

El problema que resuelve: en la MiSTer la clave de un juego de Neo Geo es el
nombre de la CARPETA del romset, y cada pack usa el suyo. El de Darksoft se
llama por setname ('fatfursp'), el @MiSTer Pack Add-on por nombre legible
('Fatal Fury Special'). Un pack de caratulas tiene que servir a los dos.

romsets.xml trae los dos nombres y ademas el japones, asi que basta con
emitirlos como alias del mismo juego: el builder agrupa por 'cloneof', elige
un representante y mete CADA alias como fila del index.tsv.

Dos decisiones que no son obvias:

  * El representante tiene que ser el ALTNAME, no el setname. elect_key()
    desempata por longitud, asi que 'fatfursp' le ganaria a 'Fatal Fury
    Special' y el identify le preguntaria a ScreenScraper por un setname de
    MAME, que en el catalogo de consola no existe. Se fuerza dandole un
    <release> solo al altname: ese campo ordena antes que la longitud, y es
    honesto, porque el altname ES el nombre comercial.

  * Las revisiones ('(set 2)', '(set 3)') se agrupan con su juego base por
    titulo normalizado, no por setname: '2020bb', '2020bba' y '2020bbh' son
    el mismo juego y deben compartir una sola caratula.
"""
import re
import sys
import xml.etree.ElementTree as ET
from xml.sax.saxutils import escape

try:
    sys.stdout.reconfigure(encoding='utf-8', errors='replace')
except Exception:
    pass

if len(sys.argv) < 3:
    sys.exit(__doc__.strip())
origen, destino = sys.argv[1], sys.argv[2]


def norm(s):
    """Titulo sin etiquetas entre parentesis o corchetes, comparable."""
    s = re.sub(r'\([^)]*\)|\[[^\]]*\]', ' ', s)
    return ' '.join(re.sub(r'[^a-z0-9]+', ' ', s.lower()).split())


romsets = []
for r in ET.parse(origen).getroot().iter('romset'):
    setname = (r.get('name') or '').strip()
    if not setname:
        continue
    altname = (r.get('altname') or '').strip() or setname
    altnamej = (r.get('altnamej') or '').strip()
    romsets.append((setname, altname, altnamej))

if not romsets:
    sys.exit('no encuentro ningun <romset> en %s' % origen)

# Agrupar por titulo del altname. Las revisiones caen con su juego base.
grupos = {}
for entrada in romsets:
    grupos.setdefault(norm(entrada[1]), []).append(entrada)

usados = set()
juegos = []          # (nombre, padre_o_vacio, con_release)
for clave in sorted(grupos):
    grupo = grupos[clave]
    # El padre es el altname mas corto del grupo: el titulo base, sin el
    # '(set 2)' que llevan las revisiones.
    padre = min((alt for _, alt, _ in grupo), key=lambda s: (len(s), s))
    if padre.lower() in usados:
        continue
    usados.add(padre.lower())
    juegos.append((padre, '', True))
    for setname, altname, altnamej in grupo:
        for alias in (setname, altname, altnamej):
            if not alias or alias.lower() in usados:
                continue
            usados.add(alias.lower())
            juegos.append((alias, padre, False))

with open(destino, 'w', encoding='utf-8') as f:
    f.write('<?xml version="1.0"?>\n<datafile>\n')
    f.write('\t<header>\n\t\t<name>Neo Geo (from romsets.xml)</name>\n'
            '\t\t<description>Generated by neogeo_dat.py</description>\n'
            '\t</header>\n')
    for nombre, padre, release in juegos:
        attr = ' name="%s"' % escape(nombre, {'"': '&quot;'})
        if padre:
            attr += ' cloneof="%s"' % escape(padre, {'"': '&quot;'})
        f.write('\t<game%s>\n' % attr)
        if release:
            f.write('\t\t<release name="%s"/>\n'
                    % escape(nombre, {'"': '&quot;'}))
        # <rom> es obligatorio: load_entries() descarta el <game> que no lo
        # tenga. Sin crc ni size, como las filas de arcade.
        f.write('\t\t<rom name="%s"/>\n' % escape(nombre, {'"': '&quot;'}))
        f.write('\t</game>\n')
    f.write('</datafile>\n')

padres = sum(1 for _, p, _ in juegos if not p)
print('%d romsets -> %d juegos, %d alias  (%s)'
      % (len(romsets), padres, len(juegos) - padres, destino))
